### PR TITLE
Changes/additions/bug fixes

### PR DESCRIPTION
**Pull request by rareaquaticbadger**
See commit notes for changes.

### CODE REVIEW

**Comment by oneillkza** [comment]
Hi Mark

It's great that you've created orderAllLinkageGroups -- I was just creating an example for orderWithinGroup, and realising that we need that.

However, there are currently some clashes, since I've been working on the package from my end. Could you please update from the main repo devel branch (resolving any conflicts) and then re-make this PR? Also please test the new orderAllLinkageGroups with the example data I've now included in the package (something like the below code should run):

data(exampleLGList)
data(exampleWCMatrix)
data(strandFrequencies)

orderedLGs <- orderAllLinkageGroups(exampleLGList, strandStateMatrix = exampleWCMatrix, strandFreqMatrix = strandFrequencies)
Also, I've fixed the example for strandSeqFreqTable, so please check that that works, and do not comment it out.

(Also note that this is a comment on Github, so if you reply by email, it'll post in the comment thread).

**Comment by oneillkza** [comment]
I believe it's possible to make some commits resolving these issues, and add them to this same pull request, actually.

**Comment by oneillkza** [comment]
One issue: we shouldn't be exporting functions like combineZeroDistContigs, divideMyChr and orderContigsGreedy. Could you please remove the @export lines from these functions, and regenerate the NAMESPACE without them exported?

**Comment by rareaquaticbadger** [comment]
Yup, I can do this.

Note that divideMyChr not called by anything else.  It's used specifically to create a filter that splits chromosomes/contigs based on a binsize, which is then used in strandSeqFreqTable.  This makes it convenient to split large chromosomes (such as human) or chimeric genomes (and potentially will be useful in porting BAIT into an R-only package).  As such it should probably retain it's @export.

Also, the orderContigsGreedy might be worth having an @export too, as it is possible users will only want to analyze a single chromosome. I can remove the export from combineZeroDistContigs though.

**Comment by oneillkza** [comment]
Sure thing -- as long as it's properly documented and we can provide an example using the existing example data.

**Comment by rareaquaticbadger** [comment]
We can provide examples so long as we can use the bam example data.

With the data we have, this would serve as an example (maybe we should have one of the bam files in the data folder?):

chrTable <- makeChrTable('/ContiBAIT/inst/extdata/StrandSeqTestData_1.bam')

splitTable <- divideMyChr(chrTable, splitBy=50000)

The first function creates a data.frame of chromosome names and lengths, and the second splits them into 50,000 bp fragments.

I can't generate and example for orderContigsGreedy, because a) the cpp script is still throwing an error, b) there is still no LG example data in the data folder of the package and c) strandFrequencies is not in the standard list format and does not have the read counts as second element. This is required for contigWeights to be calculated.  Once these are resolved, the following line should work:

orderedLG1 <- orderContigsGreedy(linkageGroupList, exampleWCMatrix, strandFrequencies, 1)

**Comment by oneillkza** [comment]
Right, I've just added the example data (including read counts).

@mgottl04  can you take a look at the C++ issue? orderWithinGroup seems to be broken even in the devel repo, not just in Mark's code.

**Comment by mgottl04** [comment]
@rareaquaticbadger  What's the error that you're getting? There is a problem in the current version of the devel branch (i.e. oneilkza/ContiBAIT/devel) which is that there is a specification clash for combineZeroDistanceContigs  and how it's called in orderContigsGreedy. The ordering functionality there is intact and currently functions as expected. 

I think the appropriate thing to do is move the combiningZeroDistanceContigs to someplace before ordering happens (essentially as soon as makes sense in the pipeline). 

I'd be happy to try to help you with solve the error you're getting, but will need more information about what happens and how to reproduce the error.

**Comment by mgottl04** [comment]
@rareaquaticbadger  One thing you can do to test orderContigsGreedy is to run it line by line, which you can do by manually assigning parameters. That way you can see what line the code is failing on.

**Comment by rareaquaticbadger** [comment]
Hi Mike. I suspect the devel branch error is because combineZeroDists requires an LG, that was deleted in your later version of orderContigsGreedy. It might be worth accepting my pull request and working from there. I reintroduced the LG, and moved from combineZeroDists to the start of the function. Going line by line everything works until the cpp is called. I get an error because $score is not generated.

**Comment by oneillkza** [comment]
Mark, can you try to `rm src/*.o` then rebuild the package? The current version of orderContigsGreedy.cpp does return $score, in both your branch and the main repo, so the only reason I can think for it not to be is if the .o files are old.

Also, can you re-sync with the upstream? I've added more example data (and there are no other changes so there shouldn't be any conflicts). Then Mike can fork your version and try and debug it.

**Comment by oneillkza** [comment]
Something like this should then work:

``` R
data(exampleStrandFreq)
# data(exampleReadCounts) # I thought these were needed, but it doesn't look like it.
data(exampleWCMatrix)
data(exampleLGList)

res <- orderAllLinkageGroups(exampleLGList, exampleWCMatrix, exampleStrandFreq)
```

**Comment by oneillkza** [comment]
So one problem that has shown up is that the parameter `strandFreqMatrix` in `orderAllLinkageGroups()` is expecting a list of two matrices (of the form of the return from `strandSeqFreq()` ), not one matrix. I think it would be better to have separate parameters here (e.g.  `strandFreqMatrix` and `strandReadMatrix`).

**Comment by mgottl04** [comment]
I just played around with it given test data from Kieran and it seems like the lines relating to combineZeroDistContigs won't work with the S4 classes (specifically readTable now appears to be a StrandStateMatrix object) that we may be using at this point. 

In any event, making the necessary changes to get those parts to run, I was able to run through the rest of the ordering function without any errors, albeit with a mountain of warnings.

I feel some of the functionality that is being introduced here breaks the cohesiveness of the function and results in a lot of unnecessary parameters being passed. I think that it would be best for maintaining readability, staying DRY and reducing unnecessary complexity (and possibility of more bugs) if we move calculating libWeight and combining zero distance contigs before flow of control reaches orderContigsGreedy.  Decoupling these distinct pieces of functionality should make testing and adding new features much less of a headache.

I've given a pass at making a more cohesive version of the orderContigsGreedy and pasted it into this gist:
https://gist.github.com/mgottl04/487821ee2cffb4cb344f

This only does what the function name suggests it will do: ordering the contigs given using a greedy algorithm. All that would need to be done to get this to work is to pass it the strand state matrix (combined or not) that you want to have ordered (sorted by libWeight or not - its first try at ordering starts by placing the first contig in the matrix that it's given).

**Comment by rareaquaticbadger** [comment]
Hi,

I merged in the upstream devel this morning and made a few changes

I deleted and recompiled orderContigsGreedy., and everything is now working fine on my branch. I have added an example to orderAllLinkageGroups.R, and it runs perfectly.  I had a slight error in combineZeroDistContigs (I used an sapply that was working in some instances, but was doing some weird stuff if only two LGs were generated), which I've fixed.  As per Kieran's suggestion I've also seperated out the list generated by strandSeqFreqTable into two variables to be passed to the function.

runContiBAIT now also works. It can be run with the following:

runContiBAIT(path='/inst/extdata', pairedEnd=F, saveName='test')

where the path specifies the location of the bam files. With the example data, this works from start to finish (including generating some of the graphs).

I didn't separate out combineZeroDistContigs from orderContigsGreedy yet, as it would still be good to have a discussion on the best way to do this.

Many of the "mountains of warnings" you're getting are coming from daisy, which is seeing quite a few NA's and returning -Inf. I'm not sure if there's a workaround (aside from using suppressWarnings()).

I've added this to the push request. Not sure if it's best to merge so we're all working on the same branch, or still keep it separate.

**Comment by oneillkza** [comment]
Thanks Mark. I'm hoping Mike should get a chance to look at this tomorrow, and am currently reviewing it myself. Just a small thing: don't forget to commit the updated DESCRIPTION file to match the current state of the repo. Right now it doesn't reflect the deletion of expandMergedContigs.R

**Comment by mgottl04** [comment]
I did a fresh clone of Mark's fork. It builds, but I can't get it to run.
Using the data in ./inst/extdata runContiBAIT crashes at line 125 of strandSeqFreqTable. resultsPos and resultsNeg are both returning a list of 0.

I tried updating all the dependent packages to no avail. Here's what I'm using:

```
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_Canada.1252 
[2] LC_CTYPE=English_Canada.1252   
[3] LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.1252    

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices
[6] utils     datasets  methods   base     

other attached packages:
 [1] contiBAIT_0.99.0     Rsamtools_1.22.0    
 [3] Biostrings_2.38.2    XVector_0.10.0      
 [5] GenomicRanges_1.22.2 GenomeInfoDb_1.6.1  
 [7] IRanges_2.4.6        S4Vectors_0.8.5     
 [9] BiocGenerics_0.16.1  BH_1.58.0-1         
[11] BiocInstaller_1.20.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.2                cluster_2.0.3             
 [3] zlibbioc_1.16.0            GenomicAlignments_1.6.1   
 [5] BiocParallel_1.4.3         colorspace_1.2-6          
 [7] clue_0.3-50                foreach_1.4.3             
 [9] caTools_1.17.1             tools_3.2.2               
[11] SummarizedExperiment_1.0.1 Biobase_2.30.0            
[13] snow_0.4-1                 KernSmooth_2.23-15        
[15] lambda.r_1.1.7             futile.logger_1.4.1       
[17] gtools_3.5.0               iterators_1.0.8           
[19] GenomicFiles_1.6.0         rtracklayer_1.30.1        
[21] codetools_0.2-14           futile.options_1.0.0      
[23] bitops_1.0-6               RCurl_1.95-4.7            
[25] TSP_1.1-3                  gdata_2.17.0              
[27] gplots_2.17.0              XML_3.98-1.3    
```

What do you guys get for resultsPos and Neg when you do a fresh clone/build of the fork? Or is this a package thing?

**Comment by mgottl04** [comment]
runContiBAIT line 49

```
bamFileList <- list.files(path=path, pattern=".bam$", full.names=TRUE)
 [1] "./inst/extdata/StrandSeqTestData_1.bam"  "./inst/extdata/StrandSeqTestData_10.bam"
 [3] "./inst/extdata/StrandSeqTestData_11.bam" "./inst/extdata/StrandSeqTestData_12.bam"
 [5] "./inst/extdata/StrandSeqTestData_13.bam" "./inst/extdata/StrandSeqTestData_14.bam"
 [7] "./inst/extdata/StrandSeqTestData_15.bam" "./inst/extdata/StrandSeqTestData_16.bam"
 [9] "./inst/extdata/StrandSeqTestData_17.bam" "./inst/extdata/StrandSeqTestData_18.bam"
[11] "./inst/extdata/StrandSeqTestData_19.bam" "./inst/extdata/StrandSeqTestData_2.bam" 
[13] "./inst/extdata/StrandSeqTestData_20.bam" "./inst/extdata/StrandSeqTestData_21.bam"
[15] "./inst/extdata/StrandSeqTestData_22.bam" "./inst/extdata/StrandSeqTestData_23.bam"
[17] "./inst/extdata/StrandSeqTestData_24.bam" "./inst/extdata/StrandSeqTestData_25.bam"
[19] "./inst/extdata/StrandSeqTestData_26.bam" "./inst/extdata/StrandSeqTestData_27.bam"
[21] "./inst/extdata/StrandSeqTestData_28.bam" "./inst/extdata/StrandSeqTestData_29.bam"
[23] "./inst/extdata/StrandSeqTestData_3.bam"  "./inst/extdata/StrandSeqTestData_30.bam"
[25] "./inst/extdata/StrandSeqTestData_31.bam" "./inst/extdata/StrandSeqTestData_32.bam"
[27] "./inst/extdata/StrandSeqTestData_33.bam" "./inst/extdata/StrandSeqTestData_34.bam"
[29] "./inst/extdata/StrandSeqTestData_35.bam" "./inst/extdata/StrandSeqTestData_36.bam"
[31] "./inst/extdata/StrandSeqTestData_37.bam" "./inst/extdata/StrandSeqTestData_38.bam"
[33] "./inst/extdata/StrandSeqTestData_4.bam"  "./inst/extdata/StrandSeqTestData_5.bam" 
[35] "./inst/extdata/StrandSeqTestData_6.bam"  "./inst/extdata/StrandSeqTestData_7.bam" 
[37] "./inst/extdata/StrandSeqTestData_8.bam"  "./inst/extdata/StrandSeqTestData_9.bam" 
```

Line 119 strandSeqFreqTable

```
bf = BamFile(fileName, yieldSize=tileChunk)

class: BamFile 
path: ./inst/extdata/StrandSeqTestData_1.bam
isOpen: FALSE 
yieldSize: 100000 
obeyQname: FALSE 
asMates: FALSE 
qnamePrefixEnd: NA 
qnameSuffixStart: NA 
```

**Comment by rareaquaticbadger** [comment]
weird...

Did you make sure that pairedEnd=F ?

I've noticed this crashes when it thinks it's getting pairedEnd data (the example data is all single ended).  The included example should have had the pairedEnd=F argument though.

Let me look into it...

**Comment by mgottl04** [comment]
Kieran thinks it may be an issue with reading files on Windows. It looks like he's not having any problems on his linux boxes.

**Comment by rareaquaticbadger** [comment]
I haven't tried this on Windows, but can definitely give it a go.

Just to be clear, if you type this it fails?:

bamFileList <- list.files(path=path, pattern=".bam$", full.names=TRUE)
strandFrequencyList <- strandSeqFreqTable(bamFileList, filter=FALSE, qual=10, pairedEnd=FALSE)

Not sure how we go about resolving issues with Windows. I can certainly try and install it on a computer here and attempt to troubleshoot.  I haven't changed this function much so it seems weird it's stopped working.

**Comment by mgottl04** [comment]
Yeah, it's strange. It seems like the call to BamFile in strandSeqFreqTable isn't working.

If it is working it its current state for both of you guys, I think the pull request could be approved. 

Regarding orderContigsGreedy, the only thing I'd want to test is whether the NA values that have been turned to 0's are properly handled in this chunk:

``` R

 #order the table entered into function and convert to factor, then add factor levels.
  linkageGroupReadTable[] <- lapply(linkageGroupReadTable[row.names(best_table)[best_order$order],], factor)
  linkageGroupReadTable <- data.frame(lapply(linkageGroupReadTable, function(x){levels(x) <- c(1,2,3); x}) )
  rownames(linkageGroupReadTable) <- row.names(best_table)[best_order$order]
```

**Comment by mgottl04** [comment]
Ahh, I just had a bit of a brainfart. I changed the default value of pairEnd in the runContiBAIT header but didn't rebuild. The function works fine with that switched after building. Thanks a lot! Potential Windows disaster averted, phew.

**Comment by mgottl04** [comment]
Continuing with running this, found a warning:

```
> reorientedGroups <- reorientLinkageGroups(linkage.groups, strandStateMatrixList[[2]])
Reorienting LG 1   Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
```

You guys get this as well? Is there any meaning behind the warning given the data? Should we have a more informative message or tweak the data so that this isn't displayed?

**Comment by mgottl04** [comment]
Regarding the sex if else: do we need to have an example data set  where they are included to demonstrate that this functionality works?

**Comment by mgottl04** [comment]
Got through it. Works fine. Approve request given current example data. I'll make some style tweaks and try to test some ordering edge cases after merge.

**Comment by rareaquaticbadger** [comment]
Great!

I've had that error before too, and it's taken me a while to track down the PairedEnd argument.  Most of our data is paired, so it makes sense for the default to be TRUE, but the example data was reduced to single end for file size limits.  It's a good beta test though; I'm going to write a check to this function so that this will throw out a more meaningful error if this happens to an end user.  I'll pull it once it's done.

For the chunk of code you want to check regarding NAs, all this code is doing is taking the linkageGroupReadTable (the first arguement that goes into orderContigsGreedy) and sorts it based on the result of best_order$order.  The NA values turned into zeros in the code should only affect the relative order shouldn't it?  All the chunk you're specifying does is to use the pre-made best order and move the rows of linkageGroupReadTable to reflect that.  This was the chunk of code I was asking for help on though: as soon as I sort linkageGroupReadTable the values are no longer factors, which throws out an error when we run daisy later on.  Ideally I just wanted to use this code:

linkageGroupReadTable <- linkageGroupReadTable[row.names(best_table)[best_order$order],]

But I couldn't because then each element in the list is a integer of type double rather than a factor.  If there's a way to make these three lines less clunky (by maintaining factored data), please change them!

**Comment by rareaquaticbadger** [comment]
The warning message always happens with reorientLinkageGroups.

This function (and reorientStrandTable that comes directly after it) needs to be improved in my opinion.  We talked about combining the two together, which makes sense.  The

no non-missing arguments to min; returning Inf

warning is something that gets spat out of daisy when there are NA values for comparison between two contigs.  In other words, if contig1 is present in libraries 1-10, but not in 11-20, and contig2 is present in 11-20, but not in 1-10, then a dissimilarity cannot be calculated and it throws out that warning.  This warning also commonly pops up when plotLGDistances is run, or any of the other functions that utilize daisy.

**Comment by mgottl04** [comment]
After the merge I'll try to make it a bit less clunky. 

Would it make sense to confirm the parameter/data at the very start of the pipeline? Not in a way that requires user input, but would just print something along the lines 
Running contiBAIT on n PairEnd files using x cores,....

I'm not sure if that would be helpful or stylistically jive with whatever bioc requires, but just an idea.

**Comment by oneillkza** [comment]
Re: sex contigs, I don't think it's necessary to demonstrate every feature of the package on the example data.

**Comment by oneillkza** [comment]
We can totally print out whatever running messages we like. BioC's only
requirements are that we use the message() function to do so.

It's worth putting something in the documentation as well.

I guess we could also try and find out if Rsamtools has a way of detecting
this?

**Pull request merged**
