### PR TITLE
Bug Fixes:

### PR DESCRIPTION
**Pull request by rareaquaticbadger**
1. prevent a crash when contigWeight is omitted from orderWithinGroup (default is NA, but would crash without giving a value).
2. CombineZeroDistances was occasionally duplicating contigs. Tracked the problem to the fact that toMerge would return values already in beenMerged, so subsetted this to prevent it from happening.

Changes:
1. Changed the list names from combineZeroDistances from a vector of contigs seperated by a "+", to a sub-setted linkage grouped convention: LG1.1, LG1.2, LG1.3, etc. for each zero distance group.
2. To achieve #3, I needed to feed the LG being analyzed to orderWithinGroup and orderContigGreedy, so added this as a parameter.
3. Made combineZeroDistances return a data.frame rather than a list to make downstream analysis easier.
4. Updated LG plotting functions to display smoother color gradient for plotting associations.
5. Changed some S4 show output. Added new object class for ordered contigs

### CODE REVIEW

**Comment by oneillkza** [comment]
Thanks Mark. Unfortunately, it looks like there are some conflicts:
1. I made the same fix to plotLGDistances you did, only slightly differently (there isn't really any need to specify number of breaks, as heatmap.2 figures that out itself).
2. Mike also added functionality to orderContigsGreedy (and possibly orderWithinGroup), but different functionality to what you added.

I can resolve 1 pretty easily, but 2 will likely take either you or Mike to sort out. Rather than kick it back to you, I'll sit down with Mike tomorrow for five minutes and do that (and check that the package all still builds).

**Comment by rareaquaticbadger** [comment]
Hey Kieran,

Buggers.  Actually, it shouldn't matter too much; almost all of the changes I made were with combineZeroDistContigs.  I only added a single argument ('lg') and a line to subset the linkageGroups within the function rather than before it (this allowed me to rename the zero distance fragments with the linkage group number, rather than a concatenated string of contigs).

If you want I'm happy to go through the changes I made, and/or help fix any conflicts.  Are the changes already on the devel branch?

I still don't know what the contig ordering functions aren't recognized when I load contiBAIT (have to source them seperately).

Cheers,

Mark

**Comment by rareaquaticbadger** [comment]
Just looked at devel branch and can see the changes.


I'll see if I can do a quick merge of our work, but if not maybe you (or both of us) can talk with Mike tomorrow.


On an related note, Mike's changed some of the formatting to include package name in the body of the function (eg daisy is changed to cluster::daisy in combineZeroDistances).  I thought this should be done using an "#' @import cluster" in the function header.  Should I be changing my scripts to use the double colon format?


 Cheers,


Mark


________________________________

**Comment by oneillkza** [comment]
Thanks Mark. Yes, please go ahead and try to merge the code, and if you can't we can all sit down and fix it tomorrow.

Re: imports, we should still be using the #' @import cluster (we can even be more specific and just import the function needed, ie #' @importFrom cluster daisy). This tells roxygen to update the imports in NAMESPACE.

**Comment by rareaquaticbadger** [comment]
Ok, will give it a go.


Re: imports.  Ok, that's what I thought.  I'll roll back the edit Mike made and just use it as an import in the header.  I think combineZeroDistContigs doesn't have much of a header as we weren't sure if we were going to combine it.  Given we've got a greedy and TSP route to clustering, it's probably best to keep this separate, but without an @export so it'll be hidden as a function.


I've checked out the devel branch so will attempt to fix the conflicts.


Cheers,


Mark



________________________________

**Comment by rareaquaticbadger** [comment]
Not sure what's going on, but if use the devel branch version where breaks are omitted from heatmap.2, the data from daisy appears to shift.


Without breaks:


[cid:d704e60e-b8d4-4cf9-85dd-ef0017029dcc]



With Breaks

[cid:3b11c96a-e8eb-4674-9a5b-a03f2b1230ca]


If I just run hist() on the daisy-transformed data, the histogram matches colorkey histogram when breaks are used.  I'm not sure why this is happening, but I think it's probably best to include the breaks line when we're running heatmap.2.


Mark



________________________________

**Pull request merged**
