### PR TITLE
Order plot tweak

### PR DESCRIPTION
**Pull request by mgottl04**
Applied diverging colour scheme to heatplot produced by Number of breaks still reduced from 100 to 12, using 11 different colours, which may still be too many. Also put contig labels back in. This functionality probably shouldn't be in orderAllLinkageGroups.

### CODE REVIEW

**Comment by oneillkza** [comment]
I think this definitely illustrates a problem, and as you say the solution is almost certainly to not have the heatmap plotting embedded in `orderAllLinkageGroups`.

We do actually have code to plot contigs within a linkage group, contained in `plotLGDistances`. It would be quite easy to run that over the results of `orderAllLinkageGroups` _post-hoc_. Also, we have an existing (and quite effective) diverging colour scheme that's implemented in `plotLGDistances`, which I think we should stick to.

**Comment by oneillkza** [comment]
@rareaquaticbadger , would you have any objection to the heatmap plotting being removed from `orderAllLinkageGroups` ? I think it would be better off going into the overarching contiBAIT function, to be run after `orderAllLinkageGroups`, by applying `plotLGDistances`.

**Comment by mgottl04** [comment]
Seems like there are 5 separate calls to heatmap.2:
Line#:File
55:plotLGDistances.R
71:plotLGDistances.R
84:plotLGDistances.R
96:plotLGDistances.R
140:orderAllLinkageGroups.R

Aside from reducing duplication, it might also be worth making a properties file for plot parameters to ensure consistency.

**Comment by oneillkza** [comment]
Yeah, consistency and non-duplication would definitely be a good idea!

If we keep everything within `plotLGDistances`, then we can have a function-internal object somewhere at the beginning with defaults. 

Or, put all the plot parameters as parameters to `plotLGDistances` (with defaults), in case users want to fiddle with them.

**Comment by mgottl04** [comment]
It seems like it would be rather straightforward to take all of the parameters used and stick them all in a YAML file. Short example:

```
>(aColorRamp <-colorRampPalette(c('#a50026','#ffffbf','#313695'))(4))
[1] "#A50026" "#E1AA8B" "#BABCB1" "#313695"

>(aYAMLColorRamp <- yaml::as.yaml(aColorRamp))
[1] "- '#A50026'\n- '#E1AA8B'\n- '#BABCB1'\n- '#313695'\n"

>(theSameColorRamp <- yaml.load(aYAMLColorRamp))
[1] "#A50026" "#E1AA8B" "#BABCB1" "#313695"
```

Probably more of nice to have though.

**Comment by oneillkza** [comment]
Totally. It just feels like overkill to me, given the relatively small number of parameters, and that they'll all be contained within one function.

**Comment by rareaquaticbadger** [comment]
So the plotting section in orderAllLinkageGroups is a bit of a remnant.  I already added that functionality to plotLGDistances (the alreadyOrdered parameter keeps the matrix in the same order as what it is given (so each element of the linkageGroupList that is returned from orderAllLinkageGroups can be put into this function).

I had some troubles doing this, which is why there are so many heatplot calls.  I couldn't find a good solution to have the dendrogram='none' options for the alreadyOrdered parameter, but I guess it would be easier to just have a parameter that toggles between 'none' or 'both' depending on the param.

**Pull request merged**
