### PR TITLE
new pull request

### PR DESCRIPTION
**Pull request by rareaquaticbadger**
Hi,

I've merged the two reorientation functions now that clusterContigs defaults to taking homozygous vs heterozygous calls.

Note that rerunning clusterContigs in the reorientation code to find misorientations was very slow and was generating multiple sub-linkage groups.  Instead I opted for a simple hclust with a cutree approach: the fragments have already been clustered (hopefully) correctly, so a less intensive clustering within the linkage groups seemed the best course. It also clustered better from what I could see of intermediate heatmaps that I made to validate.  reorientLinkageGroups now returns a list where the first element is an object of type StrandStateMatrix, and the second element is a data.frame of contigs and orientations.

### CODE REVIEW

**Comment by oneillkza** [comment]
Nice!

However, I get a few errors:
1. In the example for `contiBAIT()`, in the line calling down to `orderAllLinkageGroups()`, this crashes.
2. It looks like reorientStrandTable was removed, but the generic is still present and exported in AllGenerics (causing a warning when I run R CMD check).

**Comment by rareaquaticbadger** [comment]
Ok, I'll take a look.  Because the reorientation is now returning a list I probably missed something so orderAllLinkageGroups is passing the list rather than the first element of the list. I'll check it at work tomorrow.

I can remove the generic too; I didn't see that warning when I built it. Sorry I missed it.

**Comment by rareaquaticbadger** [comment]
Ok,

Please don't kill me.  I've added another function.  I'd been running R CMD build, not R CMD build ContiBAIT, so I was accidentally checking an old build.  Sorry about that.

It now builds ok.  There is the following warning:
Warning: replacing previous import by ‘reshape::expand’ when loading ‘contiBAIT’

I've changed many of the plotting functions to ggplot2 format, as it cleans up the code and makes the plots easier (legends just work, rownames resize etc.).  I needed to use the 'melt' function in reshape, but was getting an error if I tried @ImportFrom reshape melt. I'm not sure what other package has a reshape that's being replaced, but it doesn't seem to be called elsewhere.

The added function essentially makes a BAIT plot of the ordered contigs, and will be useful as an independent BAIT plotter.  I've added examples, created a setGeneric and given it a definition. I've also extensively showed its usage in the vignette.

The reorientation errors should now be fixed.  I'd forgotten it returned a list, so contiBAIT.R was calling a list rather than a data.frame which was causing the error.  Note the second element of this list is a data.frame of contigs and orientations that I expect will be useful in the write.bed function.

The only things now to finish is the write.bed function.

Questions:
1. Does everything need to have a setGeneric?  I can go through all functions that are missing this, examples, signatures and definitions if you would like?
2. I have found a way to add meta columns to GRanges objects.  I could convert makeChrTable and divideMyChr to return GRanges objects rather than ChrTable objects (downstream functions uses rownames of ChrTable, but would need to convert to the meta column). Is this something we should do?

**Comment by oneillkza** [comment]
To get rid of that warning (which you should do before I merge the pull request :P), in `barplotLinkageGroupCalls.R`, change `@import reshape` to `@importFrom reshape melt` (or whichever functions you need).

Also, I was getting a weird error in the vignette code, but traced it down to a version incompatibility between GenomicRanges and IRanges. With both updated, it works correctly.

If you can just get rid of that warning, I'll merge this!

**Comment by oneillkza** [comment]
Oh, and re:generics, only methods need to have generics. Functions that we don't turn into methods do not need them. I think pretty much everything we export is a method (except for `strandSeqFreqTable` which loads directly from a file).

Hmm ... `preprocessStrandTable` should be a method, actually, since we pass it a `StrandFreqMatrix`.

**Comment by rareaquaticbadger** [comment]
It doesn't let me! I initially tried using @importFrom reshape melt, and had a could not find melt error.  Switching to @import reshape worked, but I get that warning.  Not sure how to proceed.

That's what I thought about preprocessStrandTable. Will work on getting that methody.

**Comment by oneillkza** [comment]
Ah, yeah I see that. Googling around I found a fix:

`@importFrom reshape melt melt.matrix`

(This also imports the relevant version of melt for matrices.)

**Comment by rareaquaticbadger** [comment]
Should be good to go now. Passed R CMD check (2 Notes; one from the packages diagram and BH,  and the other a litany of no visible binding for global variables, mostly from ggplot2 calls).

The levels in makeChrTable were going screwy which is why the vignette had weird ideograms on the BAIT plot.  Should be fixed now.

**Pull request merged**
