### PR TITLE
-Got writeBed producing a bed-like output

### PR DESCRIPTION
**Pull request by rareaquaticbadger**
-Updated most functions to setMethods
-started adding new lines at comma sites of multi-parameter functions to make code more readable and to conform to bioconductor check.
-added OrientationFrame object definition.

### CODE REVIEW

**Comment by rareaquaticbadger** [comment]
Made a few edits because reorientLinkageGroups wasn't working on non-example data.  Only additional note I get is:
Found the following non-portable file path:
  contiBAIT/man/orderAllLinkageGroups-LinkageGroupList-StrandStateMatrix-StrandFreqMatrix-StrandReadMatrix-method.Rd

This is because I have a long string in my alias for orderAllLinkageGroups.R
#' @aliases orderAllLinkageGroups orderAllLinkageGroups,LinkageGroupList,LinkageGroupList-method,StrandStateMatrix,StrandStateMatrix-method,StrandFreqMatrix,StrandFreqMatrix-method,StrandReadMatrix,StrandReadMatrix-method

I did this because I was following the same format as other setMethod functions.  If this should be changed, please let me know.

**Comment by oneillkza** [comment]
Use this in orderAllLinkageGroups.R

``` r
#' @aliases orderAllLinkageGroups orderAllLinkageGroups,orderAllLinkageGroups-LinkageGroupList-StrandStateMatrix-StrandFreqMatrix-StrandReadMatrix-method
#' @rdname orderAllLinkageGroups
```

That specifies to use orderAllLinkageGroups.Rd as the filename (so the path is shorter than 100 bytes), but keeps the complicated alias saying that this is a method of four classes.

**Comment by oneillkza** [comment]
One other thought I had, going through the code, is that the main `contiBAIT` function should really return all the information needed for writeBed. 

Also, when I did manage to test writeBed (by running the code in the vignette and using those results), it threw an error:

``` r
writeBed(exampleChrTable, reorientedMatrix[[2]], contigOrder, fileName = '~/tmp/test.bed')
Error in .find_start_end_cols(df_colnames0, start.field0, end.field0) : 
  cannnot determine start/end columns
```

**Comment by rareaquaticbadger** [comment]
Ok, I think the issue there is you're using exampleChrTable, rather than exampleDividedChr, and because the contig names in reorientedMatrix are not present in the undivided chrTable, there are no elements being returned. Can you try with exampleDividedChr?

I'll add the aliases and repush, but please check writeBed and see if this fixes the error, otherwise I'll work on it.  It seems to be running fine on my computer...

**Comment by rareaquaticbadger** [comment]
Also, I just noticed that computeQCMatrix isn't called by any functions in the package.  I'm guessing we're ok deleting that too?

**Comment by oneillkza** [comment]
Ah, you're right about using exampleDividedChr. That now works. 

Yeah, doesn't look like anything's calling computeQCMatrix, so should be fine to delete.

One other minor comment: generally in R filenames are taken as they are, without adding extensions (as writeBed currently does). I think it's common to call the fileName parameter "file" (e.g. see `write.csv()` or `save()` )

**Comment by rareaquaticbadger** [comment]
Ok,

We're pretty close to being done, and I'm happy that this version be our 1.0.  There's still a need to get a good quality metric for writeBed, but it's not essential at the moment.

I've had a go at retooling mergeLinkageGroups, as much of it's earlier functions (to merge misoriented linkage groups) were redundant now that misoriented members now predominantly belong within the same linkage group rather than in two groups. This is because we now compare homozygous to heterozygous when running clusterContigs rather than homozygous Watson and homozygous Crick.

I've gotten rid of the paste extensions for the file names, and changed fileName to file.

Is there anything else left to do before we submit to bioC?

**Comment by oneillkza** [comment]
Great!

Re: "1.0", unfortunately we can't do that until it's accepted into Bioconductor! 

Re: what's left to do, BiocCheck is still throwing up a few issues (mainly with missing examples). I'll work on those now.

Also try and remember to use TRUE instead of T! 

You can see the issues by installing the BiocCheck package, loading it once as root (at which point it copies an executable to your R bin directory), then running `R CMD BiocCheck` in the same way as `R CMD check` (if you're interested).

**Pull request merged**
