### PR TITLE
Version 1.1.1

### PR DESCRIPTION
**Pull request by rareaquaticbadger**
Bug Fixes:
-prevented rare error where strandSeqFreqTable was crashing when there were no reads for all contigs

Major changes:
-Added table output of inversion/chimera statistics from locateMisorients
-Made method for plotContigOrder and cleaned up code

Merge remote-tracking branch 'upstream/devel'
# Please enter a commit message to explain why this merge is necessary,
# especially if it merges an updated upstream into a topic branch.
# 
# Lines starting with '#' will be ignored, and an empty message aborts
# the commit.

### CODE REVIEW

**Comment by oneillkza** [comment]
The Travis check failed, but that looks like it might be an issue with the diagram package, not your code. I've just forced a re-run, so let's see how that goes.

**Comment by rareaquaticbadger** [comment]
That's weird.

I'm pretty sure we just import diagram; it's not dependent on a version (so shouldn't have a ">=" issue).  Only BH and Rsamtools are dependent on versions (as per the DESCRIPTION file).  Diagram is only used to make a flow chart in the vignette. If it continues to be a problem, we can just replace this with an .svg that is called in the tex file.

Diagram hasn't been updated in CRAN since 2014, and has worked in previous contiBAIT builds (as well as when I ran R CMD check), so I don't know what this issue could be.

**Comment by oneillkza** [comment]
Yeah, it's almost certainly an issue with the diagram package itself, though it seems to install fine on my machine, so I don't know. It's definitely not us.

Anyway, per my email, the only thing to change before I can merge this would be to set the version number to 1.1.1 (in the NEWS and DESCRIPTION files), to match with the updated version due to Bioconductor releases.

**Comment by oneillkza** [comment]
Merged manually.

**Pull request merged**
